### ISSUE TITLE
Gradle version problem

### ISSUE THREAD

**Issue by Deneath** [airgap-it/beacon-android-sdk#11]
I'm trying to update the beacon android SDK version to the latest, but I'm getting an error:

Using multiple versions of the Android Gradle plugin(7.2.1, 7.2.2) in the same build is not allowed.

In our project, we use the 7.2.2 Gradle version.

Could you please update the gradle on your project?

**Comment by jsamol** [comment]
At first glance it looks like it could be related to [an issue in the Android Gradle Plugin](https://issuetracker.google.com/issues/231597482). If this is the cause then I'm not sure if simply updating the plugin will solve the issue in general. I have to investigate deeper, I'll let you know once I have an acceptable solution.

**Comment by jsamol** [comment]
In the end I've upgraded the plugin to the latest. Could you give `3.2.3-beta01` a try to confirm it fixes it for you too?

**Comment by Deneath** [comment]
Yeah, it works. Thank you!
