### ISSUE TITLE
Ktor versions conflict

### ISSUE THREAD

**Issue by Deneath** [airgap-it/beacon-android-sdk#14]
### Bug Report

- [x] I'm using the latest version of the SDK. 
- [x] I've seen [the docs](https://docs.walletbeacon.io) and [the demo code](https://github.com/airgap-it/beacon-android-sdk/tree/master/demo). 
- [x] I'm using the SDK directly (not via a 3rd party library or application).
    
    - [x] I've been able to confirm that the issue comes from this SDK, not the 3rd party software on top. 

#### Current Behavior

In my project I use the third-party library which uses a Ktor version 2.2. But there is Ktor version 1.6 in beacon sdk. As soon as I start using the beacon related classes, my app crashes.
[exception-logs.txt](https://github.com/airgap-it/beacon-android-sdk/files/10780097/exception-logs.txt)

If I remove this third party library (with Ktor 2.2), everything works fine. But we dont need to remove it - we need to use both libraries.
So I suggest to upgrade beacon sdk to use Ktor version 2.2 [migration guide](https://ktor.io/docs/migrating-2.html)

#### Expected Behavior

Beacon sdk uses Ktor 2.2. There is no versions conflict
#### How to Reproduce?

You can add a dependency that uses a Ktor 2.2 to the beacon sample project
#### Environment

- Device: all devices
- OS version: all versions

**Comment by jsamol** [comment]
Hi @Deneath! Thanks for pointing this out. We've just released v3.2.4 with Ktor version updated to the latest (v2.2.3), I hope this solves your problem.

**Comment by Deneath** [comment]
Brilliant! Everything works as expected. Thank you @jsamol for quick reaction.
