### ISSUE TITLE
Proguard rule has problem

### ISSUE THREAD

**Issue by SephirothLT** [airgap-it/beacon-android-sdk#6]
i'm using this sdk for dev native android app,but after add proguard-rules ,i cant get any message from the Web!

**Comment by SephirothLT** [comment]
@AndreasGassmann @godenzim

**Comment by jsamol** [comment]
Have you applied the rules listed in [the docs](https://docs.walletbeacon.io/wallet/getting-started/android/installation#proguard-and-r8) (or [README](https://github.com/airgap-it/beacon-android-sdk#proguard-and-r8))?
